export default {
    EXPERIMENT_PHASE: 'EXPERIMENT_PHASE',
    PATTERN_MEASUREMENT_UPDATE: 'PATTERN_MEASUREMENT_UPDATE',
    PATTERNS: 'PATTERNS',
    DECISION_RESULT: 'EXPERIMENT_DECISION_RESULT',
    MANUAL_DECISION: 'EXPERIMENT_MANUAL_DECISION',
};
