export default {
    APPLICATION_STATE_UPDATE: 'APPLICATION_STATE_UPDATE',
    PATTERN_MEASUREMENT: 'PATTERN_MEASUREMENT'
};

export const APPLICATION_STATE_UPDATE_TYPE = {
    OPEN_API_SPEC: 'OPEN_API_SPEC',
    PATTERNS: 'PATTERNS',
    ABSTRACT_PATTERNS: 'ABSTRACT_PATTERNS',
    PHASE: 'PHASE'
};
