export enum ApplicationPhase {
    INITIALIZATION = 'INITIALIZATION',
    PATTERN_RESOLUTION = 'PATTERN_RESOLUTION',
    WORKLOAD_GENERATION = 'WORKLOAD_GENERATION',
    REQUEST_TRANSMISSION = 'REQUEST_TRANSMISSION',
    MEASUREMENT_EVALUATION = 'MEASUREMENT_EVALUATION',
    COMPLETION = 'COMPLETION',
}
